import {
    ElAside,
    ElButton,
    ElContainer,
    ElDescriptions,
    ElDescriptionsItem,
    ElDialog,
    ElDivider,
    ElDrawer,
    ElHeader,
    ElIcon,
    ElInput,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElSubMenu,
    ElTable,
    ElTableColumn,
    ElTabPane,
    ElTabs,
    ElTag
} from "element-plus";
import 'element-plus/dist/index.css';

export default [
    ElButton,
    ElContainer,
    ElHeader,
    ElAside,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElSubMenu,
    ElIcon,
    ElTable,
    ElTableColumn,
    ElInput,
    ElTabs,
    ElTabPane,
    ElDrawer,
    ElDescriptions,
    ElDescriptionsItem,
    ElTag,
    ElDialog,
    ElDivider,
]