import {
    ElAside,
    ElButton, ElCol,
    ElContainer,
    ElDatePicker,
    ElDescriptions,
    ElDescriptionsItem,
    ElDialog,
    ElDivider,
    ElDrawer,
    ElForm,
    ElFormItem,
    ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElMain,
    ElMenu,
    ElMenuItem, ElOption,
    ElSelect,
    ElSubMenu,
    ElSwitch,
    ElTable,
    ElTableColumn,
    ElTabPane,
    ElTabs,
    ElTag
} from "element-plus";
import 'element-plus/dist/index.css';

export default [
    ElButton,
    ElContainer,
    ElHeader,
    ElAside,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElSubMenu,
    ElIcon,
    ElTable,
    ElTableColumn,
    ElInput,
    ElTabs,
    ElTabPane,
    ElDrawer,
    ElDescriptions,
    ElDescriptionsItem,
    ElTag,
    ElDialog,
    ElDivider,
    ElForm,
    ElFormItem,
    ElDatePicker,
    ElSwitch,
    ElCol,
    ElSelect,
    ElOption,
    ElImage,
]